version: "3"

services:
  proxyserver:
    build: ./loadBalancer
    ports:
      - "9000:9000"
    volumes:
      - ./loadBalancer/balancer.js:/loadBalancer/balancer.js
    networks:
      - frontend

  api1:
    build: ./apiserver
    depends_on:
      - db
      - proxyserver
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/postgres
      - PORT=8000
      - DELAY_TIME=6000
      - SECRET_MESSAGE="Hello i am server1"
      - MY_HOST_ADDRESS=http://api1:8000
      - LOAD_BALANCER_URL=http://proxyserver:9000
    networks:
      - backend
      - frontend

  api2:
    build: ./apiserver
    depends_on:
      - db
      - proxyserver
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/postgres
      - PORT=8001
      - DELAY_TIME=6000
      - SECRET_MESSAGE="Hello i am server2"
      - MY_HOST_ADDRESS=http://api2:8001
      - LOAD_BALANCER_URL=http://proxyserver:9000
    networks:
      - backend
      - frontend

  db:
    image: postgres:9.6.1
    volumes:
      - dbData:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  dbData:
networks:
  frontend:
  backend: